### ISSUE TITLE
Delete an edge

### ISSUE THREAD

**Issue by tensornetworkgui** [tensornetworkgui/tensornetworkgui.github.io#2]
It should be possible to delete an edge after you've created/connected one.

**Comment by coryell** [comment]
This is currently possible by clicking on one of the nodes on the edge, finding the edge in question on the right sidebar, and pressing delete.

**Comment by chaserileyroberts** [comment]
That's too many steps. Ideally it would be a 2 step process, just click the edge and delete it. (Or one step, if you can right click the edge to delete it.)
